package com.yellowseed.utils;

import java.io.Serializable;

@SuppressWarnings("ALL")
public class AppConstants implements Serializable {

    public static final int PERMISSION_REQUEST_CODE = 100;
    public static final String IMAGE_PATH = "image_path";
    public static final String FROM = "from";
    public static final String SIGNUP = "signup";
    public static final String CHANGE_NUMBER = "change_number";
    public static final String COLLEGE = "college";
    public static final String PLUS = "+";
    public static final String USER_TOKEN = "user_token";
    public static final String DEVICE_TOKEN = "device_token";
    public static final String DEVICE_TYPE = "Android";
    public static final int SUCCESS = 200;
    public static final int USER_NOT_VERIFIED = 407;
    public static final int USER_BLOCKED = 405;
    public static final String WELCOME = "Welcome";
    public static final String AUTHTOKEN = "AUTHTOKEN";
    public static final String FACEBOOK = "Facebook";
    public static final String SCHOOL_TYPE = "School";
    public static final String COLLEGE_TYPE = "College";
    public static final String WORK_AT_TYPE = "WorkAt";
    public static final String MOBILE_COUNTRY_CODE = "mobile_country_code";
    public static final String ID = "id";
    public static final String POST_ID = "post_id";
    public static final String TIME_ELAPSED_STRING = "time_elapsed_string";
    public static final String COMMENT_ID = "comment_id";
    public static final String ALL_STORY_LIST = "all story list";
    public static final String SHARED_ID = "shared_id";
    public static final String REASON = "reason";
    public static final String IS_USER_POST = "is_user_post";
    public static final String FROM_STORY = "from_story";
    public static final String QUESTION = "question";
    public static final String OPTION1 = "option1";
    public static final String OPTION2 = "option2";
    public static final String INITIAL_X_LOCATION = "initial_x_location";
    public static final String INITIAL_Y_LOCATION = "initial_y_location";
    public static final String INITIAL_X = "initial_x";
    public static final String INITIAL_Y = "initial_y";
    public static final String IS_MUTE_NOTIFICATION = "is mute notification";
    public static final String IS_SHOW_AWATER = "is show awater";
    public static final String IS_PRIVATE_PROFILE = "is private profile";
    public static final String IS_ALLOW_COMMENT = "is allow comment";
    public static final String IS_ALLOW_SHARING = "is allow sharing";
    public static final String IS_SAVE_GALLERY = "is save gallery";
    public static final String LAST_SEEN = "last seen";
    public static final String TAG_POST = "tag post";
    public static final String IS_CHAT_WALLPAPER = "is chat wallpaper";
    public static final String PROFILE_PHOTO = "profile photo";
    public static final String IS_MEDIA_DOWNLOAD_PRIVATE = "is media download private";
    public static final String IS_MEDIA_DOWNLOAD_GROUP = "is media download group";
    public static final String POST_DISCRIPTION = "post discription";
    public static final String POST_CHECK_IN = "post check in";
    public static final String FROM_EDIT_POST = "from edit post";
    public static final String POSITION = "position";
    public static final String POST_MODEL = "post list";
    public static final String TAG_FRIEND_LIST = "tag friend list";
    public static final String CHAT_USER_ID = "chat user id";
    public static final String PROFILE = "profile";
    public static final String ASSOC_ID = "assoc id";
    public static final String DIRECT = "direct";
    public static final String SENDER_ID = "sender id";
    public static final String NAME = "name";
    public static final String QB_ID = "qbId";
    public static final String IS_GROUP = "is group";
    public static final String CHAT_FRAGMENT = "chat fragment";
    public static final String PARTICIPANTS = "participants";
    public static final String CONTACT_CHAT_ACTIVITY = "contact chat activity";

    public static final String CHAT_FORWARD = "chat forward activity";

    public static final String ANONYMOUS_USER = "anonymous_user";
    public static final String USER_IMAGE = "user image";
    public static final String ROOM_ID = "room id";
    public static final String IS_BLOCKED = "is blocked";
    public static final String IS_FORWARD = "forward";
    public static final String IS_BROAD_CAST = "is_broadcast";
    public static final String BLOCKED_API_CALLED = "blocked api called";
    public static final String BLOCKED_STATUS = "blocked status";
    public static final String CHAT_CLEARED = "chat cleared";
    public static final String IS_MUTE = "is mute";
    public static final String NOTIFICATION_ID = "notification id";
    public static final String DARK_THEME = "dark_theme";
    public static final String IS_POLL_ADD = "is_poll_added";
    public static final String IS_FROM = "is_from";
    public static final String USER_NAME = "user_name";
    public static final String USER_PROFILE_IMAGE = "user_profile_image";
    /*It is using for Web services communication */
    private static final String TAG = "MyActivity";
    public static final String POLL = "poll";
    public static final String POLL_RESULT = "poll_result";
    public static final String LIKED_NUMBER="liked_number";
    public static final String POST = "post";
    public static boolean reportAnotherUSer = false;
    public static boolean chatsaccept = false;
    public static boolean seeUSerDetail = false;
    public static boolean clickAvatarSkip = false;
    public static boolean clickMenuItem = false;
    public static boolean clickStoryItem = false;
    public static String USER_DATA = "user_data";
    public static String GMAIL = "gmail";
    public static String USER_NUM = "user_num";
    public static String FROM_LOGIN = "from_login";
    public static String USER_ID = "user_id";
    public static String GRID = "grid";
    public static String LIST = "list";
}
